### ISSUE TITLE
macOS上正确的打开方式？

### ISSUE THREAD

**Issue by mio4** [Milloyy/ZhihuSpider#11]
1. pip install -r requirements.txt
2. 运行`python run.py`后直接报错了：

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import zhihu.spider
  File "/Users/mio/mio/02-repo/python-spider/ZhihuSpider/zhihu/spider/__init__.py", line 3, in <module>
    from zhihu.conf import config
  File "/Users/mio/mio/02-repo/python-spider/ZhihuSpider/zhihu/conf/__init__.py", line 4, in <module>
    import zhihu.conf.config as zcc
AttributeError: module 'zhihu' has no attribute 'conf'

**Comment by Milloyy** [comment]
#10

**Comment by mio4** [comment]
@Milloyy  
1.python setup.py install
2. zhihu -h 
报错：
`Traceback (most recent call last):
  File "/Users/mio/anaconda2/envs/spider/bin/zhihu", line 11, in <module>
    load_entry_point('Zhihu-Spider==6.0.1', 'console_scripts', 'zhihu')()
  File "/Users/mio/anaconda2/envs/spider/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mio/anaconda2/envs/spider/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2855, in load_entry_point
    return ep.load()
  File "/Users/mio/anaconda2/envs/spider/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2446, in load
    return self.resolve()
  File "/Users/mio/anaconda2/envs/spider/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2452, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mio/anaconda2/envs/spider/lib/python3.6/site-packages/zhihu/GrandConcourse.py", line 5, in <module>
    import zhihu.spider
  File "/Users/mio/anaconda2/envs/spider/lib/python3.6/site-packages/zhihu/spider/__init__.py", line 3, in <module>
    from zhihu.conf import config
  File "/Users/mio/anaconda2/envs/spider/lib/python3.6/site-packages/zhihu/conf/__init__.py", line 4, in <module>
    import zhihu.conf.config as zcc
AttributeError: module 'zhihu' has no attribute 'conf'`
