### ISSUE TITLE
一些链接可能会出现以下问题

### ISSUE THREAD

**Issue by Chen294** [Milloyy/ZhihuSpider#19]
https://www.zhihu.com/question/422686198/answer/1496034900
Traceback (most recent call last):
  File "XXX\Scripts\zhihu-script.py", line 33, in <module>
    sys.exit(load_entry_point('Zhihu-Favorite==1.8', 'console_scripts', 'zhihu')())
  File "XXX\lib\site-packages\zhihu_favorite-1.8-py3.8.egg\zhihu\main.py", line 107, in main
    management = get_module_instance_by_task_feature(task=url)
  File "XXX\lib\site-packages\zhihu_favorite-1.8-py3.8.egg\zhihu\spider\modules\__init__.py", line 55, in get_module_instance_by_task_feature
    return management(match_res.group(1))
  File "XXX\lib\site-packages\zhihu_favorite-1.8-py3.8.egg\zhihu\spider\management.py", line 22, in __init__
    self.title = util.getvalue(self.data, 'question/title')
  File "XXX\lib\site-packages\zhihu_favorite-1.8-py3.8.egg\zhihu\util.py", line 72, in getvalue
    a = a.get(k)
AttributeError: 'NoneType' object has no attribute 'get'

初步判定是由一些广告卡片没有正确解析所致

**Comment by Milloyy** [comment]
这个答案设置了禁止转载，API请求数据需要带cookies。

**Comment by Chen294** [comment]
谢谢作者!
